#!/usr/bin/env python3
"""Generate the top-level docker-compose.yml for an N-team CTF scaffold.

Usage:  python3 scripts/gen_compose.py [num_teams]   # default 3

Writes ./docker-compose.yml relative to the repo root.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


HEADER = """\
# Auto-generated by scripts/gen_compose.py - edit that script, not this file.
#
# Top-level orchestrator for the local Attack & Defense CTF infrastructure.
# Every team gets an SSH gateway and a vulnerable-application container slot
# attached to the shared ctf-network bridge at 10.10.0.0/16.

networks:
  ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1

volumes:
"""


VULN_TPL = """\
  team{i}-vuln:
    image: "${{VULN_IMAGE:?Set VULN_IMAGE to the vulnerable app image before starting}}"
    container_name: team{i}-vuln
    hostname: team{i}-vuln
    networks:
      ctf-network:
        ipv4_address: 10.10.{i}.3
    environment:
      - TEAM_ID={i}
      - TEAM_NAME=Team {i}
      - SERVICE_PORT=${{VULN_PORT:-8080}}
    volumes:
      - team{i}-data:/app/data
    deploy:
      resources:
        limits:
          cpus: "${{TEAM_CPU_LIMIT:-2}}"
          memory: "${{TEAM_MEM_LIMIT:-2g}}"
        reservations:
          cpus: "0.5"
          memory: 512m
    restart: unless-stopped
"""


SSH_TPL = """\
  team{i}-ssh:
    build:
      context: .
      dockerfile: teams/ssh/Dockerfile
      args:
        TEAM_USER: ctfuser
        TEAM_PASS: team{i}pass
        TEAM_NAME: team{i}
    image: sandcastle/team{i}-ssh-gateway
    container_name: team{i}-ssh
    hostname: team{i}
    networks:
      ctf-network:
        ipv4_address: 10.10.{i}.2
    ports:
      - "{ssh_port}:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: "${{TEAM_CPU_LIMIT:-2}}"
          memory: "${{TEAM_MEM_LIMIT:-2g}}"
        reservations:
          cpus: "0.5"
          memory: 512m
    restart: unless-stopped
"""


def render(num_teams: int) -> str:
    out: list[str] = [HEADER]
    for i in range(1, num_teams + 1):
        out.append(f"  team{i}-data:\n")
    out.append("\nservices:\n")
    for i in range(1, num_teams + 1):
        out.append(VULN_TPL.format(i=i))
    for i in range(1, num_teams + 1):
        out.append(SSH_TPL.format(i=i, ssh_port=2200 + i))
    return "".join(out)


def main() -> None:
    num_teams = int(sys.argv[1]) if len(sys.argv) > 1 else 3
    if num_teams < 1 or num_teams > 16:
        raise SystemExit("num_teams must be between 1 and 16")
    out_path = REPO_ROOT / "docker-compose.yml"
    out_path.write_text(render(num_teams))
    print(f"wrote {out_path} for {num_teams} teams")


if __name__ == "__main__":
    main()
