#!/usr/bin/env python3
"""Generate the top-level docker-compose.yml for an N-team simulation.

Usage:  python3 scripts/gen_compose.py [num_teams]   # default 3

Writes ./docker-compose.yml relative to the repo root.
"""

from __future__ import annotations

import sys
from pathlib import Path
from textwrap import dedent

REPO_ROOT = Path(__file__).resolve().parent.parent


HEADER = """\
# Auto-generated by scripts/gen_compose.py — edit that script, not this file.
#
# Top-level orchestrator for the local Attack & Defense CTF simulation.
# Every team gets two containers (SSH gateway + vulnerable notes service)
# attached to the shared ctf-network bridge at 10.10.0.0/16.

networks:
  ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1

volumes:
  gameserver-data:
"""


GAMESERVER_TPL = """\
services:
  gameserver:
    build: ./gameserver
    image: ad-ctf/gameserver
    container_name: gameserver
    hostname: gameserver
    networks:
      ctf-network:
        ipv4_address: 10.10.0.2
    ports:
      - "8080:8080"
    environment:
      - NUM_TEAMS={num_teams}
      - TICK_DURATION={tick_duration}
      - FLAG_EXPIRY_ROUNDS={flag_expiry}
      - GAMESERVER_DB=/app/data/gameserver.sqlite
      - AUTO_START=true
    volumes:
      - gameserver-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on: {{}}
"""


VULN_FIRST_TPL = """\
  team{i}-vuln:
    build: ./services/notes-service
    image: ad-ctf/notes-service
    container_name: team{i}-vuln
    hostname: team{i}-vuln
    networks:
      ctf-network:
        ipv4_address: 10.10.{i}.3
    environment:
      - TEAM_NAME=Team {i}
      - NOTES_ADMIN_TOKEN=admin-{i}
    volumes:
      - team{i}-data:/app/data
    restart: unless-stopped
"""


VULN_TPL = """\
  team{i}-vuln:
    image: ad-ctf/notes-service
    container_name: team{i}-vuln
    hostname: team{i}-vuln
    depends_on:
      - team1-vuln
    networks:
      ctf-network:
        ipv4_address: 10.10.{i}.3
    environment:
      - TEAM_NAME=Team {i}
      - NOTES_ADMIN_TOKEN=admin-{i}
    volumes:
      - team{i}-data:/app/data
    restart: unless-stopped
"""


SSH_FIRST_TPL = """\
  team{i}-ssh:
    build:
      context: ./teams/ssh
      args:
        TEAM_USER: ctfuser
        TEAM_PASS: team{i}pass
        TEAM_NAME: team{i}
    image: ad-ctf/ssh-gateway
    container_name: team{i}-ssh
    hostname: team{i}
    networks:
      ctf-network:
        ipv4_address: 10.10.{i}.2
    ports:
      - "{ssh_port}:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/notes-service:/home/ctfuser/service:ro
    cap_add:
      - NET_ADMIN
    depends_on:
      - team{i}-vuln
    restart: unless-stopped
"""


SSH_TPL = """\
  team{i}-ssh:
    image: ad-ctf/ssh-gateway
    container_name: team{i}-ssh
    hostname: team{i}
    networks:
      ctf-network:
        ipv4_address: 10.10.{i}.2
    ports:
      - "{ssh_port}:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/notes-service:/home/ctfuser/service:ro
    environment:
      - TEAM_USER=ctfuser
      - TEAM_NAME=team{i}
    cap_add:
      - NET_ADMIN
    depends_on:
      - team{i}-vuln
      - team1-ssh
    restart: unless-stopped
"""


def render(num_teams: int, tick_duration: int = 30, flag_expiry: int = 5) -> str:
    out: list[str] = [HEADER]
    out.append("\n")
    for i in range(1, num_teams + 1):
        out.append(f"  team{i}-data:\n")
    out.append("\n")
    out.append(GAMESERVER_TPL.format(
        num_teams=num_teams, tick_duration=tick_duration, flag_expiry=flag_expiry
    ))
    for i in range(1, num_teams + 1):
        tpl = VULN_FIRST_TPL if i == 1 else VULN_TPL
        out.append(tpl.format(i=i))
    for i in range(1, num_teams + 1):
        tpl = SSH_FIRST_TPL if i == 1 else SSH_TPL
        out.append(tpl.format(i=i, ssh_port=2200 + i))
    return "".join(out)


def main() -> None:
    num_teams = int(sys.argv[1]) if len(sys.argv) > 1 else 3
    if num_teams < 1 or num_teams > 16:
        raise SystemExit("num_teams must be between 1 and 16")
    out_path = REPO_ROOT / "docker-compose.yml"
    out_path.write_text(render(num_teams))
    print(f"wrote {out_path} for {num_teams} teams")


if __name__ == "__main__":
    main()
