#!/usr/bin/env bash
# Generate a local Sandcastle Attack & Defense scaffold for N teams.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEAMS_DIR="${ROOT}/teams"
GENERATED_TEAMS_DIR="${TEAMS_DIR}/generated"
DEFAULT_SERVICE_TEMPLATE="${ROOT}/services/example-vuln"
COMPOSE_FILE="${ROOT}/docker-compose.yml"
DEFAULT_TEAMS=3
MAX_TEAMS=250
NUM_TEAMS="${DEFAULT_TEAMS}"
TEMPLATE_DIR="${DEFAULT_SERVICE_TEMPLATE}"
OVERWRITE_SERVICES=0
PRUNE_EXTRA_TEAMS=1

usage() {
    cat <<EOF
Usage:
  ./scripts/setup.sh --teams N
  ./scripts/setup.sh -t N

Options:
  --teams, -t   Number of teams to generate. Defaults to ${DEFAULT_TEAMS}.
  --template    Service template directory to copy. Defaults to services/example-vuln.
  --overwrite-services
                Replace existing teams/generated/team<N>/example-vuln directories with the template.
  --no-prune    Keep generated teams/generated/team<N> directories above the requested count.
  --help, -h    Show this help text.

Compatibility:
  ./scripts/setup.sh N  also works for the old positional form.
EOF
}

die() {
    echo "setup.sh: $*" >&2
    exit 1
}

parse_args() {
    local value=""
    local provided=0

    while (($#)); do
        case "$1" in
            --teams|-t)
                [[ $# -ge 2 ]] || die "$1 requires a value"
                value="$2"
                provided=1
                shift 2
                ;;
            --teams=*)
                value="${1#*=}"
                provided=1
                shift
                ;;
            --template)
                [[ $# -ge 2 ]] || die "$1 requires a value"
                TEMPLATE_DIR="$2"
                shift 2
                ;;
            --template=*)
                TEMPLATE_DIR="${1#*=}"
                shift
                ;;
            --overwrite-services)
                OVERWRITE_SERVICES=1
                shift
                ;;
            --no-prune)
                PRUNE_EXTRA_TEAMS=0
                shift
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            [0-9]*)
                [[ "${provided}" -eq 0 ]] || die "team count provided more than once"
                value="$1"
                provided=1
                shift
                ;;
            *)
                die "unknown argument: $1"
                ;;
        esac
    done

    if [[ "${provided}" -eq 0 ]]; then
        value="${DEFAULT_TEAMS}"
    fi

    [[ -n "${value}" ]] || die "team count must be provided"
    [[ "${value}" =~ ^[0-9]+$ ]] || die "team count must be a positive integer"
    value="$((10#${value}))"
    ((value >= 1 && value <= MAX_TEAMS)) || die "team count must be between 1 and ${MAX_TEAMS}"

    if [[ "${TEMPLATE_DIR}" != /* ]]; then
        TEMPLATE_DIR="${ROOT}/${TEMPLATE_DIR}"
    fi
    [[ -d "${TEMPLATE_DIR}" ]] || die "missing vulnerable service template: ${TEMPLATE_DIR}"

    NUM_TEAMS="${value}"
}

is_generated_team_dir() {
    local team_dir="$1"
    [[ -f "${team_dir}/.sandcastle-generated" ]]
}

prune_extra_teams() {
    local teams="$1"
    local team_dir name team_num

    [[ "${PRUNE_EXTRA_TEAMS}" -eq 1 ]] || return

    shopt -s nullglob
    for team_dir in "${GENERATED_TEAMS_DIR}"/team*; do
        [[ -d "${team_dir}" ]] || continue
        name="$(basename "${team_dir}")"
        [[ "${name}" =~ ^team([0-9]+)$ ]] || continue
        team_num="${BASH_REMATCH[1]}"
        team_num="$((10#${team_num}))"

        if ((team_num > teams)); then
            if is_generated_team_dir "${team_dir}"; then
                rm -rf "${team_dir}"
            else
                echo "[!] Keeping unmarked extra team directory: ${team_dir}" >&2
            fi
        fi
    done
    shopt -u nullglob
}

remove_legacy_generated_teams() {
    local team_dir

    shopt -s nullglob
    for team_dir in "${TEAMS_DIR}"/team*; do
        [[ -d "${team_dir}" ]] || continue
        if is_generated_team_dir "${team_dir}"; then
            rm -rf "${team_dir}"
        else
            echo "[!] Keeping unmarked legacy team directory: ${team_dir}" >&2
        fi
    done
    shopt -u nullglob
}

copy_service_template() {
    local team_dir="$1"
    local service_dir="${team_dir}/example-vuln"
    local legacy_service_dir="${team_dir}/service"

    if [[ -d "${legacy_service_dir}" ]]; then
        rm -rf "${legacy_service_dir}"
    fi

    if [[ -d "${service_dir}" && "${OVERWRITE_SERVICES}" -eq 0 ]]; then
        return
    fi

    mkdir -p "${service_dir}"
    if [[ "${OVERWRITE_SERVICES}" -eq 1 ]]; then
        find "${service_dir}" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
    fi
    cp -a "${TEMPLATE_DIR}/." "${service_dir}/"
}

write_team_service_compose() {
    local team_num="$1"
    local team_dir="$2"
    local service_dir="${team_dir}/example-vuln"

    mkdir -p "${service_dir}"
    cat > "${service_dir}/docker-compose.yml" <<EOF
# Generated by scripts/setup.sh for Team ${team_num}.
# Teams run this from inside team${team_num}-vuln after patching:
#   cd ~/example-vuln && docker compose up -d --build

name: sandcastle-team${team_num}

services:
  team${team_num}-vuln-app:
    build:
      context: .
    image: sandcastle/team${team_num}-vuln-app:latest
    container_name: team${team_num}-vuln-app
    network_mode: "container:team${team_num}-vuln"
    environment:
      TEAM_ID: "${team_num}"
      TEAM_NAME: "Team ${team_num}"
      SERVICE_PORT: "8080"
      SECRET_KEY: "sandcastle-team${team_num}-dev-secret"
    volumes:
      - team-data:/app/data
    labels:
      sandcastle.role: "vuln-app"
      sandcastle.team: "team${team_num}"
    restart: unless-stopped

volumes:
  team-data:
    name: sandcastle_team${team_num}-data
    labels:
      sandcastle.role: "vuln-data"
      sandcastle.team: "team${team_num}"
EOF
}

write_compose() {
    local teams="$1"

    cat > "${COMPOSE_FILE}" <<EOF
# Auto-generated by ./scripts/setup.sh. Re-run that script instead of editing this file.
#
# Local Attack & Defense CTF topology:
#   - one firewall container routing all inter-team traffic
#   - one SSH gateway container per team
#   - one vulnerable Linux machine per team
#   - deterministic addresses on 10.10.0.0/16

name: sandcastle

networks:
  ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1

services:
  firewall:
    build:
      context: .
      dockerfile: docker/firewall/Dockerfile
    image: sandcastle/firewall:latest
    container_name: sandcastle-firewall
    hostname: sandcastle-firewall
    networks:
      ctf-network:
        ipv4_address: 10.10.0.2
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped
EOF

    local i
    for ((i = 1; i <= teams; i++)); do
        printf '\n' >> "${COMPOSE_FILE}"

        cat >> "${COMPOSE_FILE}" <<EOF
  team${i}-vuln:
    build:
      context: .
      dockerfile: docker/vuln/Dockerfile
      args:
        TEAM_ID: "${i}"
        TEAM_NAME: "team${i}"
        TEAM_USER: "team${i}"
        TEAM_PASS: "team${i}pass"
        TEAM_UID: "1000"
    image: sandcastle/team${i}-vuln:latest
    container_name: team${i}-vuln
    hostname: team${i}-vuln
    depends_on:
      - firewall
    networks:
      ctf-network:
        ipv4_address: 10.10.${i}.3
    environment:
      GATEWAY_OVERRIDE: "10.10.0.2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./teams/generated/team${i}/example-vuln:/home/team${i}/example-vuln
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  team${i}-ssh:
    build:
      context: .
      dockerfile: docker/ssh/Dockerfile
      args:
        TEAM_ID: "${i}"
        TEAM_NAME: "team${i}"
        TEAM_USER: "team${i}"
        TEAM_PASS: "team${i}pass"
        TEAM_UID: "1000"
    image: sandcastle/team${i}-ssh:latest
    container_name: team${i}-ssh
    hostname: team${i}-ssh
    depends_on:
      - firewall
      - team${i}-vuln
    networks:
      ctf-network:
        ipv4_address: 10.10.${i}.2
    environment:
      GATEWAY_OVERRIDE: "10.10.0.2"
    ports:
      - "$((2200 + i)):22"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
EOF
    done

    cat >> "${COMPOSE_FILE}" <<'EOF'

  monitor:
    build:
      context: ./monitor
    image: sandcastle/monitor:latest
    container_name: sandcastle-monitor
    hostname: sandcastle-monitor
    networks:
      ctf-network:
        ipv4_address: 10.10.0.3
    ports:
      - "6789:6789"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
EOF
}

print_summary() {
    local teams="$1"
    local i

    echo
    echo "Generated ${teams} team(s) + firewall."
    echo
    printf '%-14s %-15s %-12s\n' "Container" "IP" "Host access"
    printf '%-14s %-15s %-12s\n' "---------" "--" "-----------"
    printf '%-14s %-15s %-12s\n' "firewall" "10.10.0.2" "(internal)"
    for ((i = 1; i <= teams; i++)); do
        printf '%-14s %-15s %-12s\n' \
            "team${i}-ssh" "10.10.${i}.2" "port $((2200 + i))"
        printf '%-14s %-15s %-12s\n' \
            "team${i}-vuln" "10.10.${i}.3" "(internal)"
    done
    echo
    echo "Next:"
    echo "  docker compose up --build"
    echo "  ssh -p 2201 team1@localhost"
    echo "  ssh team1@team1-vuln"
    echo "  cd ~/example-vuln && docker compose up -d --build"
}

main() {
    local teams
    parse_args "$@"
    teams="${NUM_TEAMS}"

    mkdir -p "${GENERATED_TEAMS_DIR}"
    remove_legacy_generated_teams
    prune_extra_teams "${teams}"

    local i team_dir
    for ((i = 1; i <= teams; i++)); do
        team_dir="${GENERATED_TEAMS_DIR}/team${i}"
        mkdir -p "${team_dir}"
        printf 'Generated by ./scripts/setup.sh for team%s.\n' "${i}" > "${team_dir}/.sandcastle-generated"
        copy_service_template "${team_dir}"
        write_team_service_compose "${i}" "${team_dir}"
    done

    write_compose "${teams}"
    print_summary "${teams}"
}

main "$@"
