#!/usr/bin/env bash
# Generate a local Sandcastle Attack & Defense scaffold for N teams.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEAMS_DIR="${ROOT}/teams"
GENERATED_TEAMS_DIR="${TEAMS_DIR}/generated"
DEFAULT_SERVICE_TEMPLATE="${ROOT}/services/example-vuln"
COMPOSE_FILE="${ROOT}/docker-compose.yml"
DEFAULT_TEAMS=3
MAX_TEAMS=250
NUM_TEAMS="${DEFAULT_TEAMS}"
TEMPLATE_DIR="${DEFAULT_SERVICE_TEMPLATE}"
OVERWRITE_SERVICES=0
PRUNE_EXTRA_TEAMS=1

usage() {
    cat <<EOF
Usage:
  ./scripts/setup.sh --teams N
  ./scripts/setup.sh -t N

Options:
  --teams, -t   Number of teams to generate. Defaults to ${DEFAULT_TEAMS}.
  --template    Service template directory to copy. Defaults to services/example-vuln.
  --overwrite-services
                Replace existing teams/generated/team<N>/service directories with the template.
  --no-prune    Keep generated teams/generated/team<N> directories above the requested count.
  --help, -h    Show this help text.

Compatibility:
  ./scripts/setup.sh N  also works for the old positional form.
EOF
}

die() {
    echo "setup.sh: $*" >&2
    exit 1
}

parse_args() {
    local value=""
    local provided=0

    while (($#)); do
        case "$1" in
            --teams|-t)
                [[ $# -ge 2 ]] || die "$1 requires a value"
                value="$2"
                provided=1
                shift 2
                ;;
            --teams=*)
                value="${1#*=}"
                provided=1
                shift
                ;;
            --template)
                [[ $# -ge 2 ]] || die "$1 requires a value"
                TEMPLATE_DIR="$2"
                shift 2
                ;;
            --template=*)
                TEMPLATE_DIR="${1#*=}"
                shift
                ;;
            --overwrite-services)
                OVERWRITE_SERVICES=1
                shift
                ;;
            --no-prune)
                PRUNE_EXTRA_TEAMS=0
                shift
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            [0-9]*)
                [[ "${provided}" -eq 0 ]] || die "team count provided more than once"
                value="$1"
                provided=1
                shift
                ;;
            *)
                die "unknown argument: $1"
                ;;
        esac
    done

    if [[ "${provided}" -eq 0 ]]; then
        value="${DEFAULT_TEAMS}"
    fi

    [[ -n "${value}" ]] || die "team count must be provided"
    [[ "${value}" =~ ^[0-9]+$ ]] || die "team count must be a positive integer"
    value="$((10#${value}))"
    ((value >= 1 && value <= MAX_TEAMS)) || die "team count must be between 1 and ${MAX_TEAMS}"

    if [[ "${TEMPLATE_DIR}" != /* ]]; then
        TEMPLATE_DIR="${ROOT}/${TEMPLATE_DIR}"
    fi
    [[ -d "${TEMPLATE_DIR}" ]] || die "missing vulnerable service template: ${TEMPLATE_DIR}"

    NUM_TEAMS="${value}"
}

is_generated_team_dir() {
    local team_dir="$1"
    [[ -f "${team_dir}/.sandcastle-generated" ]]
}

prune_extra_teams() {
    local teams="$1"
    local team_dir name team_num

    [[ "${PRUNE_EXTRA_TEAMS}" -eq 1 ]] || return

    shopt -s nullglob
    for team_dir in "${GENERATED_TEAMS_DIR}"/team*; do
        [[ -d "${team_dir}" ]] || continue
        name="$(basename "${team_dir}")"
        [[ "${name}" =~ ^team([0-9]+)$ ]] || continue
        team_num="${BASH_REMATCH[1]}"
        team_num="$((10#${team_num}))"

        if ((team_num > teams)); then
            if is_generated_team_dir "${team_dir}"; then
                rm -rf "${team_dir}"
            else
                echo "[!] Keeping unmarked extra team directory: ${team_dir}" >&2
            fi
        fi
    done
    shopt -u nullglob
}

remove_legacy_generated_teams() {
    local team_dir

    shopt -s nullglob
    for team_dir in "${TEAMS_DIR}"/team*; do
        [[ -d "${team_dir}" ]] || continue
        if is_generated_team_dir "${team_dir}"; then
            rm -rf "${team_dir}"
        else
            echo "[!] Keeping unmarked legacy team directory: ${team_dir}" >&2
        fi
    done
    shopt -u nullglob
}

copy_service_template() {
    local team_dir="$1"
    local service_dir="${team_dir}/service"

    if [[ -d "${service_dir}" && "${OVERWRITE_SERVICES}" -eq 0 ]]; then
        return
    fi

    if [[ -d "${service_dir}" ]]; then
        rm -rf "${service_dir}"
    fi
    mkdir -p "${service_dir}"
    cp -a "${TEMPLATE_DIR}/." "${service_dir}/"
}

write_team_service_compose() {
    local team_num="$1"
    local team_dir="$2"
    local service_dir="${team_dir}/service"

    mkdir -p "${service_dir}"
    cat > "${service_dir}/sandcastle-compose.yml" <<EOF
# Generated by scripts/setup.sh for Team ${team_num}.
# Teams can run this from inside SSH after patching:
#   cd ~/service && redeploy-service

services:
  team${team_num}-vuln:
    build:
      context: .
    image: sandcastle/team${team_num}-vuln:latest
    container_name: team${team_num}-vuln
    hostname: team${team_num}-vuln
    networks:
      ctf-network:
        ipv4_address: 10.10.${team_num}.3
    environment:
      TEAM_ID: "${team_num}"
      TEAM_NAME: "Team ${team_num}"
      SERVICE_PORT: "8080"
      SECRET_KEY: "sandcastle-team${team_num}-dev-secret"
    volumes:
      - team-data:/app/data
    restart: unless-stopped

networks:
  ctf-network:
    external: true
    name: sandcastle_ctf-network

volumes:
  team-data:
    external: true
    name: sandcastle_team${team_num}-data
EOF
}

write_compose() {
    local teams="$1"

    cat > "${COMPOSE_FILE}" <<EOF
# Auto-generated by ./scripts/setup.sh. Re-run that script instead of editing this file.
#
# Local Attack & Defense CTF topology:
#   - one SSH gateway container per team
#   - one vulnerable service container per team
#   - deterministic addresses on 10.10.0.0/16

name: sandcastle

networks:
  ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1

volumes:
EOF

    local i
    for ((i = 1; i <= teams; i++)); do
        printf '  team%d-data:\n' "${i}" >> "${COMPOSE_FILE}"
    done

    printf '\nservices:\n' >> "${COMPOSE_FILE}"
    for ((i = 1; i <= teams; i++)); do
        cat >> "${COMPOSE_FILE}" <<EOF
  team${i}-vuln:
    build:
      context: ./teams/generated/team${i}/service
    image: sandcastle/team${i}-vuln:latest
    container_name: team${i}-vuln
    hostname: team${i}-vuln
    networks:
      ctf-network:
        ipv4_address: 10.10.${i}.3
    environment:
      TEAM_ID: "${i}"
      TEAM_NAME: "Team ${i}"
      SERVICE_PORT: "8080"
      SECRET_KEY: "sandcastle-team${i}-dev-secret"
    volumes:
      - team${i}-data:/app/data
    restart: unless-stopped

  team${i}-ssh:
    build:
      context: .
      dockerfile: docker/ssh/Dockerfile
      args:
        TEAM_ID: "${i}"
        TEAM_NAME: "team${i}"
        TEAM_USER: "team${i}"
        TEAM_PASS: "team${i}pass"
        TEAM_UID: "1000"
    image: sandcastle/team${i}-ssh:latest
    container_name: team${i}-ssh
    hostname: team${i}-ssh
    depends_on:
      - team${i}-vuln
    networks:
      ctf-network:
        ipv4_address: 10.10.${i}.2
    ports:
      - "$((2200 + i)):22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./teams/generated/team${i}/service:/home/team${i}/service
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

EOF
    done

    local tmp_compose
    tmp_compose="$(mktemp "${COMPOSE_FILE}.XXXXXX")"
    awk 'NF || seen { print } { seen = 1 }' "${COMPOSE_FILE}" > "${tmp_compose}"
    mv "${tmp_compose}" "${COMPOSE_FILE}"
}

print_summary() {
    local teams="$1"
    local i

    echo
    echo "Generated ${teams} team(s)."
    echo
    printf '%-8s %-15s %-15s %-9s %-12s %-12s\n' "Team" "SSH IP" "Service IP" "SSH Port" "Username" "Password"
    printf '%-8s %-15s %-15s %-9s %-12s %-12s\n' "----" "------" "----------" "--------" "--------" "--------"
    for ((i = 1; i <= teams; i++)); do
        printf '%-8s %-15s %-15s %-9s %-12s %-12s\n' \
            "team${i}" "10.10.${i}.2" "10.10.${i}.3" "$((2200 + i))" "team${i}" "team${i}pass"
    done
    echo
    echo "Next:"
    echo "  docker compose up --build"
    echo "  ssh -p 2201 team1@localhost"
}

main() {
    local teams
    parse_args "$@"
    teams="${NUM_TEAMS}"

    mkdir -p "${GENERATED_TEAMS_DIR}"
    remove_legacy_generated_teams
    prune_extra_teams "${teams}"

    local i team_dir
    for ((i = 1; i <= teams; i++)); do
        team_dir="${GENERATED_TEAMS_DIR}/team${i}"
        mkdir -p "${team_dir}"
        printf 'Generated by ./scripts/setup.sh for team%s.\n' "${i}" > "${team_dir}/.sandcastle-generated"
        copy_service_template "${team_dir}"
        write_team_service_compose "${i}" "${team_dir}"
    done

    write_compose "${teams}"
    print_summary "${teams}"
}

main "$@"
